// Code generated by "stringer -type=Event -linecomment"; DO NOT EDIT.

package xbox

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventCrossPress-0]
	_ = x[EventCrossRelease-1]
	_ = x[EventCirclePress-2]
	_ = x[EventCircleRelease-3]
	_ = x[EventSquarePress-4]
	_ = x[EventSquareRelease-5]
	_ = x[EventTrianglePress-6]
	_ = x[EventTriangleRelease-7]
	_ = x[EventL1Press-8]
	_ = x[EventL1Release-9]
	_ = x[EventL2Press-10]
	_ = x[EventL2Release-11]
	_ = x[EventL3Press-12]
	_ = x[EventL3Release-13]
	_ = x[EventR1Press-14]
	_ = x[EventR1Release-15]
	_ = x[EventR2Press-16]
	_ = x[EventR2Release-17]
	_ = x[EventR3Press-18]
	_ = x[EventR3Release-19]
	_ = x[EventDpadUpPress-20]
	_ = x[EventDpadUpRelease-21]
	_ = x[EventDpadDownPress-22]
	_ = x[EventDpadDownRelease-23]
	_ = x[EventDpadLeftPress-24]
	_ = x[EventDpadLeftRelease-25]
	_ = x[EventDpadRightPress-26]
	_ = x[EventDpadRightRelease-27]
	_ = x[EventSharePress-28]
	_ = x[EventShareRelease-29]
	_ = x[EventOptionsPress-30]
	_ = x[EventOptionsRelease-31]
	_ = x[EventTouchpadPress-32]
	_ = x[EventTouchpadRelease-33]
	_ = x[EventPSPress-34]
	_ = x[EventPSRelease-35]
	_ = x[EventLeftPaddlePress-36]
	_ = x[EventLeftPaddleRelease-37]
	_ = x[EventRightPaddlePress-38]
	_ = x[EventRightPaddleRelease-39]
}

const _Event_name = "cross.presscross.releasecircle.presscircle.releasesquare.presssquare.releasetriangle.presstriangle.releasel1.pressl1.releasel2.pressl2.releasel3.pressl3.releaser1.pressr1.releaser2.pressr2.releaser3.pressr3.releasedpad_up.pressdpad_up.releasedpad_down.pressdpad_down.releasedpad_left.pressdpad_left.releasedpad_right.pressdpad_right.releaseshare.pressshare.releaseoptions.pressoptions.releasetouchpad.presstouchpad.releaseps.pressps.releaseleft_paddle.pressleft_paddle.releaseright_paddle.pressright_paddle.release"

var _Event_index = [...]uint16{0, 11, 24, 36, 50, 62, 76, 90, 106, 114, 124, 132, 142, 150, 160, 168, 178, 186, 196, 204, 214, 227, 242, 257, 274, 289, 306, 322, 340, 351, 364, 377, 392, 406, 422, 430, 440, 457, 476, 494, 514}

func (i Event) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Event_index)-1 {
		return "Event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Event_name[_Event_index[idx]:_Event_index[idx+1]]
}
